[project]
name = "medvqa-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "bert-score>=0.3.13",
    "datasets>=5.0.1",
    "evaluate>=0.4.6",
    "fvcore>=0.1.5.post20221221",
    "ipython>=9.17.1",
    "matplotlib>=3.11.2",
    "nltk>=3.10.3",
    "opencv-python-headless>=5.0.0.93",
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
    "rouge-score>=0.1.2",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
    "transformers>=5.17.0",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]
